### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by prakhar21** [suriyadeepan/practical_seq2seq#17]
what version of tensorflow are you using ? 
While running the code ,I am getting the below mentioned error.
```
<log> Building Graph </log>Traceback (most recent call last):
  File "train.py", line 55, in <module>
    sess = model.train(train_batch_gen, val_batch_gen)
  File "/home/prakhar/utilities/IOT/PythonUtilPlugin/scripts/chat/mycreation/seq2seq_wrapper.py", line 138, in train
    sess.run(tf.global_variables_initializer())
AttributeError: 'module' object has no attribute 'global_variables_initializer'

```

**Comment by suriyadeepan** [comment]
0.12.0

**Comment by prakhar21** [comment]
Upgraded to 0.12.0. That issue is resolved, i guess global_variables_initializer() had some different naming convention in previous versions. But, still I am getting the below mentioned error.
```
<log> Building Graph </log>
<log> Training started </log>
Traceback (most recent call last):
  File "train.py", line 55, in <module>
    sess = model.train(train_batch_gen, val_batch_gen)
  File "/home/prakhar/utilities/IOT/PythonUtilPlugin/scripts/chat/mycreation/seq2seq_wrapper.py", line 145, in train
    self.train_batch(sess, train_set)
  File "/home/prakhar/utilities/IOT/PythonUtilPlugin/scripts/chat/mycreation/seq2seq_wrapper.py", line 99, in train_batch
    batchX, batchY = train_batch_gen.__next__()
AttributeError: 'generator' object has no attribute '__next__'

```

**Comment by suriyadeepan** [comment]
python 3

**Comment by prakhar21** [comment]
got it. thanks. made the necessary changes. working now.
