### ISSUE TITLE
Attribute error on Tensorflow 1.0 version

### ISSUE THREAD

**Issue by nicks165** [suriyadeepan/practical_seq2seq#20]
I am facing the following problem while executing
<log> Building Graph Traceback (most recent call last):
  File "03-Twitter-chatbot.py", line 33, in <module>
    num_layers=3
  File "/home/testxprt/practical_seq2seq/seq2seq_wrapper.py", line 79, in __init__
    __graph__()
  File "/home/testxprt/practical_seq2seq/seq2seq_wrapper.py", line 45, in __graph__
    basic_cell = tf.nn.rnn_cell.DropoutWrapper(
AttributeError: module 'tensorflow.python.ops.nn' has no attribute 'rnn_cell'

**Comment by nicks165** [comment]
I have intsalled TF0.12. They have moved their rnn_cell and all modules to contrib.
